### ISSUE TITLE
Will be maintained ?

### ISSUE THREAD

**Issue by delacosta456** [eldertek/duplicatefinder#1]
Thanks

**Comment by eldertek** [comment]
Is this for ok ?

**Comment by delacosta456** [comment]
oh my god .. i didn't know what happened to my message.

i was asking if the this fork is correctly working (and will continue) with NC from NC26 to NC8

Thanks

**Comment by eldertek** [comment]
> oh my god .. i didn't know what happened to my message.
> 
> i was asking if the this fork is correctly working (and will continue) with NC from NC26 to NC8
> 
> Thanks

it works with NC26 and NC27, and i hope to keep it working for as long as possible

A new update will be soon available directly from the nextcloud app store, I got the maintainer grade from them. So keep in touch your apps ;)

(The new update : fix translation in admin and add support of last versions)

**Comment by delacosta456** [comment]
hi ok.. that id very nice
and many thanks for the work

**Comment by eldertek** [comment]
Your welcome, you can close issue if all is okay for you ;)

**Comment by eldertek** [comment]
@delacosta456 you can find working version here
https://github.com/eldertek/duplicatefindx

**Comment by delacosta456** [comment]
hi @eldertek thanks for the update

I am closing the issue

**Comment by eldertek** [comment]
@delacosta456 Don't forget to star the project ☺️

**Comment by delacosta456** [comment]
Just for info is it the only project you are interested about ? they some nice useful app that have been abandoned that you may also wanted to maintain

**Comment by eldertek** [comment]
Add me on discord we can talk : @eldertek

**Comment by delacosta456** [comment]
hi @eldertek i added you on discord but haven't yet receive response from you
