### ISSUE TITLE
Duplicate Finder Algorithm: Understanding Behavior and Folder Differentiation

### ISSUE THREAD

**Issue by bmeloney** [eldertek/duplicatefinder#1]
Hello:  Sorry to title this as such.  I want to engage you via the "Ask Questions and Discuss" button but that did not connect.

Duplicate finder located a number of Dups during the first few hours of operation but then did not report any more.  My question is not a criticism - I hope to better understand the algorithm so that I can set my expectations correctly.

It appears that the duplicates that were found are/were located in different folders or directories.  Does you algorithm differentiate dups in the same folders/directories?

Thanks

- Bill
bmeloney@gmail.com

**Comment by eldertek** [comment]
Hello,
As marked in the readme, the detection is working like 3 ways. All duplicates are detected by hash calculation, it can be files in the same or different directory, if you don't have duplicates anymore showing it is good to clear duplicates list with occ (readme) then do the initial research of duplicates.

I hope I answered you.

**Comment by bmeloney** [comment]
Excellent response.  Thank you.

**Comment by eldertek** [comment]
Closing as completed, have a nice day !
