### ISSUE TITLE
[Bug] - Deduplicated files stays on the left pannel until page reload

### ISSUE THREAD

**Issue by Dremor** [eldertek/duplicatefinder#104]
**Describe the bug**
When taking care of duplicates, de-duplicated files stays on the left list as "unacknowledged" until the page is reloaded. Thus it is quite hard to know which file has already been de-duplicated or not.

**To Reproduce**
1. Have multiple files with multiple duplicate
2. Delete all duplicate of a file
3. Take a look at the left list => File is still in the left "unacknowledged" list

**Expected behavior**
File is removed from the left "unacknowledged" list. Maybe switch to the next duplicate in the list could be welcome.

**Screenshots**
Before de-duplication:
![image](https://github.com/user-attachments/assets/e7236b67-c46d-466e-aa74-a02031bba539)

After de-duplication:
![image](https://github.com/user-attachments/assets/9a0f3832-8dfa-4e47-94d4-548224cd7302)

**Versions**
- Nextcloud 30
- Duplicate Finder 1.2.8

**Additional context**
Reloading the page remove them. Probably a missing data reload.

**Comment by eldertek** [comment]
Already fixed in v1.2.9
