### ISSUE TITLE
[Feature Request] - Exclude specific folder from duplicate scan

### ISSUE THREAD

**Issue by Dremor** [eldertek/duplicatefinder#105]
I use Nextcloud to save my Seedvault Android backups, and it often result in chunks with the same size and signature (they are not delta backups).

It would greatly help to be able to exclude specific folders from scan to avoid having to acknowledge all those legit duplicates.

Example of those "false positives":

![image](https://github.com/user-attachments/assets/bb9b1bc5-39b9-4a00-8d10-0c814442b51e)

**Comment by eldertek** [comment]
Hi,

I'm pleased to inform you that the Duplicate Finder app already supports excluding specific folders from duplicate scans. To prevent a folder from being scanned, simply place a `.nodupefinder` file inside the desired folder. Here's how you can do it:

1. **Navigate to the Folder**: Go to the folder you want to exclude from the duplicate scan in your Nextcloud instance.
2. **Create the `.nodupefinder` File**:
   - You can create an empty file named `.nodupefinder` within the folder.
3. **Verify Exclusion**: After adding the `.nodupefinder` file, the Duplicate Finder should automatically exclude this folder from future scans. You won't need to acknowledge duplicates within this folder, effectively eliminating the false positives you’ve been encountering.

**Comment by Dremor** [comment]
Oh, Nice 😃

**Comment by eldertek** [comment]
Closing as completed, please star the project !

**Comment by Dremor** [comment]
Well, this doesn't seem to work. I added a `.nodupefinder` file in my backup folder, and there is still a ton of duplicates from that folder in the list.

**Comment by eldertek** [comment]
Did you clear duplicates and then scanned again ?

**Comment by Dremor** [comment]
And how can I do that. With occ ?

**Comment by eldertek** [comment]
In your Nextcloud settings, you have the Duplicate Finder's settings. You can clear and then find all duplicates.

With occ, it's written in the Readme.

**Comment by Dremor** [comment]
I see, I was expecting for it to be in the app options on the duplicate finder page.

It works since then.

**Comment by eldertek** [comment]
I’ve implemented the ability to filter files and exclude specific folders directly from the web interface. You can now configure this feature easily without needing to create .nodupefinder files manually.

This enhancement is available starting with version 1.4.0. Please update your app and access the new settings under the Duplicate Finder’s web interface. Let me know if you encounter any issues or need further assistance.
