### ISSUE TITLE
[Bug] - Wrongful classification as duplicate

### ISSUE THREAD

**Issue by Toastyyy3** [eldertek/duplicatefinder#107]
**Describe the bug**
I just tried using the app a little and wanted to double check as it seemed odd that the nextcloud app apparently uploaded every single picture twice with the same name which already seems odd as linux doesn't even allow that. So I checked the directory and the file just exists once. The path given in the duplicates is identical (see screenshot).

**To Reproduce**
Use duplicate finder

**Expected behavior**
Only show existing duplicates.

**Screenshots**
<img width="530" alt="Bildschirmfoto 2024-12-18 um 12 04 40" src="https://github.com/user-attachments/assets/c3f32119-8514-4742-8697-90a038184dea" />

**Versions**
- Nextcloud 30.0.4
- Duplicate Finder 1.2.9

**Additional context**
I already tried clearing all duplicates in the settings and then initiating a new search by "Find all duplicates". When trying occ duplicates:find-all, I get the following error:

There are no commands defined in the "duplicates" namespace.

**Comment by eldertek** [comment]
Do you have the issue on v1.3.1 ? 

Clear nextcloud.log
Set log level to debug
Delete all duplicates
Initiate a scan

At the end share me the nextcloud.log

**Comment by Toastyyy3** [comment]
Yes, unfortunately still occuring.
Attached you find the log.

[debug.log](https://github.com/user-attachments/files/18259619/debug.log)

**Comment by eldertek** [comment]
Could you try v1.4.0, and same step as before :

Clear nextcloud.log
Set log level to debug
Delete all duplicates
Initiate a scan

At the end share me the nextcloud.log

**Comment by Toastyyy3** [comment]
Amazing, couldn't spot any non-duplicates for now. Great work man! Thank you so much, gonna close this for now.

**Comment by eldertek** [comment]
Thanks for your feedback and for confirming that the issue is resolved with v1.4.0 !
If you found the app helpful, it would mean a lot if you could give the project a ⭐ on GitHub.
