### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by livier** [eldertek/duplicatefinder#11]
I used this extension some months ago, I want it another time now. Try to reinstall. 

Une erreur s'est produite pendant la demande. Impossible de poursuivre.

Nextcloud 26.0.5 
I others info needed, please help for the way to get them

**Comment by eldertek** [comment]
Hello, please try to install with latest Nextcloud (27).

**Comment by livier** [comment]
Now on Nextcloud 27.1.1
Same anwer
Still on php 8.0.16 (in the hands of my VPS provider)
What else to say ?

**Comment by eldertek** [comment]
Can you clear the logs, then try to install duplicate finder and after share the log file here please =)

**Comment by eldertek** [comment]
Closed due to inactivity
