### ISSUE TITLE
[Request] - Add regex or wildcard support in search for filenames (e.g., IMG*.jpg)

### ISSUE THREAD

**Issue by 6lv1-blr** [eldertek/duplicatefinder#114]
Currently, the search functionality does not support regex or wildcard patterns for filenames. This limitation makes it difficult to filter files based on patterns, such as searching for all images starting with IMG (IMG*.jpg).

Steps to Reproduce:
    Attempt to search for files using a pattern, such as IMG*.jpg or similar regex syntax.
    Observe that the search does not return expected results, as wildcard or regex is not recognized.

Expected Behavior:
The search bar should support regex or at least wildcard patterns (e.g., * and ?), enabling more flexible and powerful search capabilities. For example:

    IMG*.jpg should return all files starting with "IMG" and ending with ".jpg".
    *.jpg should return all .jpg files.

ideally a mode for accepting regex for advanced users could be perfect

Merci pour le travail

**Comment by eldertek** [comment]
Hi, added in v1.5.2 !
