### ISSUE TITLE
Add possibility to acknowledge duplicates

### ISSUE THREAD

**Issue by funkyferdy** [eldertek/duplicatefinder#13]
It would be cool to have a possibility to remeber a duplicate as Acknowledged. It can be legit to have a duplicate file. You should be able to mark a duplicate find as "Acknowledged". So this duplicate should not come in the main lists of duplicates anymore. perhaps in another subpage as "Acknowledged Duplicates" to delete the Acknowledge again.

**Comment by eldertek** [comment]
Yes, that does sound like a useful feature. I'll look into it when I have some time. =)

**Comment by eldertek** [comment]
Added by https://github.com/eldertek/duplicatefinder/pull/14
