### ISSUE TITLE
[bug] Duplicatefinder does not show duplicate

### ISSUE THREAD

**Issue by funkyferdy** [eldertek/duplicatefinder#15]
in version  1.0.7. how im supposed to see if its really a duplicate? I think is the change introduced in 

https://github.com/eldertek/duplicatefinder/pull/14 

![ksnip_20231029-202144](https://github.com/eldertek/duplicatefinder/assets/22144187/bf46fb20-8772-4262-8859-6d9cd776c432)

**Comment by eldertek** [comment]
What did you to have this screenshot please ?

**Comment by funkyferdy** [comment]
Hello, i tried to delete cache but no luck. the json looks like this (always only one file in array):

![2023-10-30 16_15_47-Window](https://github.com/eldertek/duplicatefinder/assets/22144187/b6695117-593c-4783-9150-1684e8a96fe1)

Nextcloud is version 27.1.2

**Comment by eldertek** [comment]
The issue was caused by a weird detection, I suggest you to clear duplicates (clear -f using occ) and then do an initial scan (find-all using occ), you can find more docs in readme.md.

**Comment by funkyferdy** [comment]
Thanks, unfortunately my installation is a hetzner storage share and i have only limited access to CLI / occ.
This command you are mentioning is not on the list of allowed occ commands. A little button in the management section would do the trick :)

**Comment by eldertek** [comment]
I made that functionality yesterday, I was waiting for the translation to be updated to put the package on nextcloud, but I will update it right now so you can directly clear duplicates then initial scan them from webadmin. 

Watch your app store, the update will be asked.

Get me informed then ;)

**Comment by funkyferdy** [comment]
Works for me! Great Extension for Nextcloud now :)

**Comment by eldertek** [comment]
Great ! Please star the project =) to support my work
