### ISSUE TITLE
Cannot declare class SearchDuplicates

### ISSUE THREAD

**Issue by piojan** [eldertek/duplicatefinder#18]
After upgrading to 1.0.8 I can see such errors from cron.php:

```
PHP Fatal error:  Cannot declare class SearchDuplicates, because the name is already in use in <path_removed>/apps/duplicatefinder/lib/BackgroundJob/SearchDuplicates.php on line 12

PHP Fatal error:  Cannot declare class ClearDuplicates, because the name is already in use in <path_removed>/apps/duplicatefinder/lib/Command/ClearDuplicates.php on line 12
```

**Comment by kriegerse** [comment]
I can confirm this and see the same error after updating to 1.0.8 on docker NC 27.1.3 also from occ command. 

```
www-data@f0cdf5e93397:~/html$ ./occ app:update --all
duplicatefinder new version available: 1.0.8
duplicatefinder updated

www-data@f0cdf5e93397:~/html$ ./occ status 
PHP Fatal error:  Cannot declare class ClearDuplicates, because the name is already in use in /var/www/html/custom_apps/duplicatefinder/lib/Command/ClearDuplicates.php on line 12
```

 reverted back to 1.0.7.

**Comment by eldertek** [comment]
Thanks for the issue, i am focusing on it !

**Comment by eldertek** [comment]
Is the the duplicates UI working or you can't access it ?

**Comment by msviba** [comment]
hi, I have same problem:
`/usr/local/bin/php -c /usr/local/etc/php-cloud.ini --define apc.enable_cli=1 /var/cloud/nc/cron.php`

> PHP Fatal error:  Cannot declare class SearchDuplicates, because the name is already in use in /var/cloud/nc/apps/duplicatefinder/lib/BackgroundJob/SearchDuplicates.php on line 12

**Comment by eldertek** [comment]
Added v1.0.9 to Nextcloud Appstore, you can update =)

**Comment by teemue** [comment]
Happens still after updating

**Comment by eldertek** [comment]
Give the log please

**Comment by eldertek** [comment]
> Happens still after updating
> 
> E: The logs showed that the app had clogged nc background jobs from running for a while. I removed this app, forced bg job and installed the app again. Seems to work so far.

Is the issue fix or not ?

**Comment by teemue** [comment]
> > Happens still after updating
> > 
> > E: The logs showed that the app had clogged nc background jobs from running for a while. I removed this app, forced bg job and installed the app again. Seems to work so far.
> 
> Is the issue fix or not ?

Pretty sure it's fixed. Must have been some cache-related problem.

**Comment by kriegerse** [comment]
@eldertek - I can confirm your fix worked. Updated from 1.0.7 to 1.0.9 and did not see any issues anymore.
Thanks for your fast reaction. :+1:

**Comment by eldertek** [comment]
> @eldertek - I can confirm your fix worked. Updated from 1.0.7 to 1.0.9 and did not see any issues anymore.
> Thanks for your fast reaction. :+1: 

Thanks
