### ISSUE TITLE
duplicate:list -u USER shows other users dups, not just the user given

### ISSUE THREAD

**Issue by david-55-munro** [eldertek/duplicatefinder#19]
running duplicate:list -u USER on the command line shows other users dups and so the browser interface which limits the number shown can show none for the user if the other user has lots of dups. I have app version 1.0.7 installed on nc 26.0.6

**Comment by david-55-munro** [comment]
It looks like it lists first the selected user's dups, then dups between the two users, then only the other user's dups.

**Comment by eldertek** [comment]
Was the files shared or on mounted point ?

**Comment by david-55-munro** [comment]
This is a small personal installation so only 4 users with shared folders but no externally mounted file systems. However I have used .nodupefinder to exclude the shared folders. The dups between users include the default sample files and these are displayed to each user as a single file dup in the browser gui as in issue #15. Your URL times out due to the number of dups found in the other user - they have been copying folders of photos around rather than moving, hence interest in this app.

sudo -u www-data php occ duplicate:list -u David 

produces screeds of 

3a1606d3586acd7f96567397e4e316971ec8e336b4120008a04b07c5fac16e63(file_hash)
     /Chris/files/Pictures/PhotoSync/OnePlus ONEPLUS A5010/WhatsApp Images/IMG-20221114-WA0002.jpg
     /David/files/Photos/WhatsApp Photos/2022/11/IMG-20221114-WA0002.jpg

followed by just Chris dups

c870d6a19e869bca6af89ed541f176daabecf9cf9a33d1010e40a1badbdbea93(file_hash)
     /Chris/files/Pictures/My pictures/2021/2021-6/P6020040 (1).JPG
     /Chris/files/Pictures/My pictures/2021/2021-6/P6020040.JPG
     /Chris/files/Pictures/Olympus Workspace/P6020040.JPG

I don't think it should be showing dups between users unless specifically set by an option.

Happy to try any suggested patches. Will look at the code myself.

**Comment by david-55-munro** [comment]
![image](https://github.com/eldertek/duplicatefinder/assets/122156412/f8e8dc85-8e19-4a4b-bd3f-5bf872c2c85e)

**Comment by eldertek** [comment]
Paging would be a good idea to fix your first issue (I will add it further)

can you update to v1.0.9, then clear all duplicates and then search all from webadmin, say me if it continues to give you multiple duplicates

**Comment by david-55-munro** [comment]
These are the only errors in the log with log level at 0. I don't think they are relevant.

{"reqId":"ZUOYHt97eTMcA0MotAAUmwAACwI","level":0,"time":"2023-11-02T12:37:50+00:00","remoteAddr":"192.168.1.40","user":"David","app":"PHP","method":"GET","url":"/nextcloud/apps/duplicatefinder/api/duplicates/all","message":"Return type of OCA\\DuplicateFinder\\Db\\EEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/duplicatefinder/lib/Db/EEntity.php#173","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"26.0.6.1","data":{"app":"PHP"}}
{"reqId":"FpYW9TCkDS9JjUCICaif","level":0,"time":"2023-11-02T12:45:05+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Return type of OCA\\DuplicateFinder\\Db\\EEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/duplicatefinder/lib/Db/EEntity.php#173","userAgent":"--","version":"26.0.6.1","data":{"app":"PHP"}}
{"reqId":"ZUOYHt97eTMcA0MotAAUmwAACwI","level":0,"time":"2023-11-02T12:48:32+00:00","remoteAddr":"192.168.1.40","user":"David","app":"PHP","method":"GET","url":"/nextcloud/apps/duplicatefinder/api/duplicates/all","message":"Return type of OCA\\DuplicateFinder\\Utils\\JSONDateTime::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/duplicatefinder/lib/Utils/JSONDateTime.php#6","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"26.0.6.1","data":{"app":"PHP"}}

**Comment by eldertek** [comment]
Mmmmh weird 🤔 can you contact me on discord, we'll try to fix the issue ? #eldertek
