### ISSUE TITLE
OCP\BackgroundJob\Job::$time must not be accessed before initialization

### ISSUE THREAD

**Issue by tfvlrue** [eldertek/duplicatefinder#22]
Hi,
I'm seeing this error when running the Nextcloud cron job with the Duplicate Finder app enabled:

```
Error: Typed property OCP\BackgroundJob\Job::$time must not be accessed before initialization in /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php:102
Stack trace:
#0 /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#1 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#2 {main}
```

If I disable Duplicate Finder, the error stops happening. I just recently updated to 1.0.9. Let me know what other information I can provide.

Thanks,
Luke

**Comment by eldertek** [comment]
Thanks for the issue, i am focusing on it !
