### ISSUE TITLE
dup count limit on the browser page should not include acknowledged dups

### ISSUE THREAD

**Issue by david-55-munro** [eldertek/duplicatefinder#25]
The 20 limit on dups displayed on the browser page includes acknowledged dups so get to 20 acknowledged dups and no more unacknowledged are shown.

![Screenshot from 2023-11-04 13-43-41](https://github.com/eldertek/duplicatefinder/assets/122156412/59d20d4f-0e82-4c51-b755-ae3d8631021c)

**Comment by eldertek** [comment]
Should be fixed in 1.1.2, can you let me know ?
