### ISSUE TITLE
Open preview of file(s)

### ISSUE THREAD

**Issue by keunes** [eldertek/duplicatefinder#33]
Hello,
I would like to request functionality to quickly open (a preview of) the files. If a duplicate file exists with two slightly different names, it'd be helpful to be able to quickly check the contents of the file(s) in question.

Many thanks for working making & maintaining this!

**Comment by eldertek** [comment]
Hello, more precision please ? (Sorrry French native) 🥲

**Comment by keunes** [comment]
Not entirely sure how, but let me try:
When you open a duplicate, you see the two cards each about a file (with the hash and path). In addition to the 'delete' buttons, it would be helpful to have a 'preview' or 'open' button. Clicking on it would then open a modal or sidebar, or a new tab, in which the file is displayed.

That way I can easily & quickly see the content, such that I make a better decision about which location I should keep, and which I should delete. Making that decision only based on the path & filename (without knowing the contents of the file) is sometimes a bit hard.

**Comment by eldertek** [comment]
Will the button be displayed next to each file ? 

It will be useless, no ? You'll get multiple preview buttons to see in reality the same file BC its a duplicate...

May one preview button for each duplicate ?

**Comment by keunes** [comment]
> May one preview button for each duplicate ?

Yeah, that's probably better.

Maybe then a button that 'reveals' a sidebar(?)

**Comment by eldertek** [comment]
I will prefer opening a new tab, else it will be time-consuming to integrate on the mobile (sidebar)
