### ISSUE TITLE
missing description of aknowledged and unaknowledged entries in side bar

### ISSUE THREAD

**Issue by peteho** [eldertek/duplicatefinder#36]
I am missing the description of the aknownledged and unaknowledged entries in the side bar.
As far as I understand, all duplicates that have been found are listed under "unaknowledged".
If an entry is aknowledged, what exactly happens then? Is it automatically deleted and if so, which version is kept (first or second)?
Could you please explain how this works.

**Comment by eldertek** [comment]
It is only a hint for the user, it separates acknowledged from unacknowledged.

From a system point of view, when new files appear as duplicated, they are added to the actual unacknowledged or acknowledged stack based on user choice.

**Comment by peteho** [comment]
OK, thank you. But in general, which version of the duplicates is kept?

**Comment by eldertek** [comment]
I don't understand your question

**Comment by eldertek** [comment]
You always have to manually delete your duplicates, the clean-up background job is for cleaning the database (sometimes there are files detected as duplicates but they don't exist anymore, the job "repairs" that. But it doesn't delete existing files/duplicates.

**Comment by peteho** [comment]
Thank you, now it is clear for me. I was hoping, that there is some kind of automatic cleanup.

**Comment by eldertek** [comment]
It will be too hard to maintain, what user really want to keep.
