### ISSUE TITLE
Popups block Delete button

### ISSUE THREAD

**Issue by peteho** [eldertek/duplicatefinder#37]
As you can see, the "Duplicate deleted" popups block the "Delete" button, if you delete too fast.

![image](https://github.com/eldertek/duplicatefinder/assets/42569835/279f1e3a-a563-4d4f-adb5-257918c9ab1a)

Maybe you can move the popup or the button to the other side.

**Comment by eldertek** [comment]
I will try to reduce count and delays

**Comment by eldertek** [comment]
The issue was fixed by version 1.1.5 but the only nextcloud version supported by the update will be Nc28.

Popups will be limited to 2 at the same time.
