### ISSUE TITLE
Preview not found

### ISSUE THREAD

**Issue by peteho** [eldertek/duplicatefinder#38]
Clicking on the "Show Preview" link does not work for me.
A new browser tab opens, but the image is not found.
The URL looks strange to me, also the "Port 80" cannot work on my system.
 
![image](https://github.com/eldertek/duplicatefinder/assets/42569835/8261917e-3ca8-4caf-ad31-3594e2fbd109)

**Comment by eldertek** [comment]
What's URL of your NC ?

**Comment by peteho** [comment]
For example this **https://fuzzi/nextcloud** , which is only reachable from my internal network.
If I try to preview an image the following url is generated:
https://fuzzi/nextcloud/index.php/remote.php/webdav/%2FPhotos%2F2018%2F08%2F18-08-11%2009-28-20%2046f2.jpg
But it is not reachable. Maybe the reverse proxy (haproxy), that is "between" the browser and the apache nextcloud webserver needs some redirection rules, that I am not aware of. On the other hand, all other services like caldav, carddav and file sharing work as expected.
How should the URL look like?

**Comment by eldertek** [comment]
Try to download the file from nextcloud "files" then give me the link of the downloaded file.

**Comment by eldertek** [comment]
What is your NC version ?

**Comment by peteho** [comment]
[Nextcloud Hub 6] (27.1.4)

**Comment by peteho** [comment]
No, same error.

**Comment by eldertek** [comment]
https://docs.nextcloud.com/server/20/user_manual/en/files/access_webdav.html

Your instance should be handle what's described in the link.

Try to look your redirection rules

**Comment by peteho** [comment]
I have already tried WebDav and it works.
If I change your preview URL like this:
https://fuzzi/nextcloud//remote.php/webdav/Photos/2018/12/18-12-27%2019-13-23%203ee0.jpg
a download dialog pops up. I had to remove the "index.php" and change "%2F" to "/".

**Comment by eldertek** [comment]
Okay thanks I'll try when having time to fix that on app side.

**Comment by keunes** [comment]
Hello

Just chipping in to say that the way previews are opened is somewhat unexpected for me:

Current:
https://cloud.keunes.com/remote.php/webdav/%2Fadmin%2FHuurgedoe%2Finternet%2Btelefonie%2F2019-09-24.pdf

Expected:
https://cloud.keunes.com/apps/files/?dir=/admin/Huurgedoe/internet%2Btelefonie&openfile=9878

In other words, when I requested this feature I hoped it would open the files app. Would that maybe be an option?

**Comment by joepitt91** [comment]
> I have already tried WebDav and it works. If I change your preview URL like this: https://fuzzi/nextcloud//remote.php/webdav/Photos/2018/12/18-12-27%2019-13-23%203ee0.jpg a download dialog pops up. I had to remove the "index.php" and change "%2F" to "/".

For me I'm not getting index.php in the URL, but do have to replace all occurrences of `%2F` with `/` for the preview to load.

**Comment by eldertek** [comment]
The issue was fixed by version 1.1.5 but the only nextcloud version supported by the update will be Nc28.

When clicking show preview, it will open the preview app if the file format is supported. There is a known issue: where unsupported mimetype cannot be opened and throw an error in console. [An issue is opened to fix it. ](https://github.com/nextcloud/viewer/issues/1579)
