### ISSUE TITLE
Rasberry Pi/Nextcloud goes into '504 Gateway Time-out' after opening DuplicateFinder app

### ISSUE THREAD

**Issue by keunes** [eldertek/duplicatefinder#41]
Hello,

I've enabled the duplicate finder and probably have quite a few duplicates. So I probably need this app :P 

However, after I open the app, the following happens:
* I see twice on screen the error something like 'Couldn't fetch list of acknowledged duplicates'
* I see a bunch of hashes appearing on the left side
* NC becomes unresponsive

At that point, refreshing will throw a "504 Gateway Time-out" from Nginx.

I suspect my little Raspberry Pi 3 goes crazy with the amount of duplicates it's trying to find or show. I've tried this two times now, after a night of not accessing my instance, Nextcloud is accessible again.

Would it be possible to investigate potential performance issues, see if whatever process might be running after opening the Duplicate Finder app could be throttled?

**Comment by eldertek** [comment]
Do you have any logs ?

**Comment by keunes** [comment]
It looks like this time it didn't become unaccessible when opening the app. It was slow to respond, however.

From right after I opened, I see a whole bunch of these in the logs:
```
Debug
PHP
2023-12-09T21:48:05+0100
Return type of OCA\DuplicateFinder\Db\EEntity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/html/custom_apps/duplicatefinder/lib/Db/EEntity.php#173
Debug
PHP
2023-12-09T21:48:05+0100
Return type of OCA\DuplicateFinder\Utils\JSONDateTime::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/html/custom_apps/duplicatefinder/lib/Utils/JSONDateTime.php#6
```

I count about three of these per second, until 21:48:31 (I.e. for 25s).

And then
```
Fout
files
2023-12-09T21:48:39+0100
OC\User\NoUserException: Backends provided no user object

    <<closure>>

    OC\Files\Node\Root->getUserFolder("bytehamster")

    /var/www/html/lib/private/Files/Node/LazyFolder.php - line 74:

    call_user_func_array([ [ "OC\\Fil ... "], [ "bytehamster"])

    /var/www/html/lib/private/Files/Node/LazyRoot.php - line 40:

    OC\Files\Node\LazyFolder->__call("getUserFolder", [ "bytehamster"])

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FolderService.php - line 40:

    OC\Files\Node\LazyRoot->getUserFolder("bytehamster")

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FileInfoService.php - line 280:

    OCA\DuplicateFinder\Service\FolderService->getNodeByFileInfo([ "OCA\\Dupl ... 9], "keunes")

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FileDuplicateService.php - line 109:

    OCA\DuplicateFinder\Service\FileInfoService->hasAccessRight([ "OCA\\Dupl ... 9], "keunes")

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FileDuplicateService.php - line 73:

    OCA\DuplicateFinder\Service\FileDuplicateService->stripFilesWithoutAccessRights([ "OCA\\Dupl ... 4], "keunes")

    /var/www/html/custom_apps/duplicatefinder/lib/Controller/DuplicateApiController.php - line 54:

    OCA\DuplicateFinder\Service\FileDuplicateService->findAll("acknowledged", "keunes", 1, 30, true)

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 230:

    OCA\DuplicateFinder\Controller\DuplicateApiController->list(1, 30, "acknowledged")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 137:

    OC\AppFramework\Http\Dispatcher->executeController([ "OCA\\Dupl ... "], "list")

    /var/www/html/lib/private/AppFramework/App.php - line 183:

    OC\AppFramework\Http\Dispatcher->dispatch([ "OCA\\Dupl ... "], "list")

    /var/www/html/lib/private/Route/Router.php - line 315:

    OC\AppFramework\App::main("OCA\\Duplic ... r", "list", [ "OC\\AppFr ... "], [ "acknowled ... "])

    /var/www/html/lib/base.php - line 1068:

    OC\Route\Router->match("/apps/dupli ... d")

    /var/www/html/index.php - line 36:

    OC::handleRequest()
```

And

```
Fout
duplicatefinder
2023-12-09T21:48:39+0100
OC\User\NoUserException: Backends provided no user object

    <<closure>>

    OC\Files\Node\Root->getUserFolder("bytehamster")

    /var/www/html/lib/private/Files/Node/LazyFolder.php - line 74:

    call_user_func_array([ [ "OC\\Fil ... "], [ "bytehamster"])

    /var/www/html/lib/private/Files/Node/LazyRoot.php - line 40:

    OC\Files\Node\LazyFolder->__call("getUserFolder", [ "bytehamster"])

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FolderService.php - line 40:

    OC\Files\Node\LazyRoot->getUserFolder("bytehamster")

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FileInfoService.php - line 280:

    OCA\DuplicateFinder\Service\FolderService->getNodeByFileInfo([ "OCA\\Dupl ... 9], "keunes")

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FileDuplicateService.php - line 109:

    OCA\DuplicateFinder\Service\FileInfoService->hasAccessRight([ "OCA\\Dupl ... 9], "keunes")

    /var/www/html/custom_apps/duplicatefinder/lib/Service/FileDuplicateService.php - line 73:

    OCA\DuplicateFinder\Service\FileDuplicateService->stripFilesWithoutAccessRights([ "OCA\\Dupl ... 4], "keunes")

    /var/www/html/custom_apps/duplicatefinder/lib/Controller/DuplicateApiController.php - line 54:

    OCA\DuplicateFinder\Service\FileDuplicateService->findAll("acknowledged", "keunes", 1, 30, true)

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 230:

    OCA\DuplicateFinder\Controller\DuplicateApiController->list(1, 30, "acknowledged")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 137:

    OC\AppFramework\Http\Dispatcher->executeController([ "OCA\\Dupl ... "], "list")

    /var/www/html/lib/private/AppFramework/App.php - line 183:

    OC\AppFramework\Http\Dispatcher->dispatch([ "OCA\\Dupl ... "], "list")

    /var/www/html/lib/private/Route/Router.php - line 315:

    OC\AppFramework\App::main("OCA\\Duplic ... r", "list", [ "OC\\AppFr ... "], [ "acknowled ... "])

    /var/www/html/lib/base.php - line 1068:

    OC\Route\Router->match("/apps/dupli ... d")

    /var/www/html/index.php - line 36:

    OC::handleRequest()
```

And then a whole bunch of this (always together, every couple of seconds):
```
Debug
core
2023-12-09T21:48:49+0100
OC_Image->fixOrientation() Orientation: -1
Debug
core
2023-12-09T21:48:49+0100
OC_Image->fixOrientation() Image is not a JPEG.
```
As well as
```
Debug
core
2023-12-09T21:49:56+0100
OC_Image::fixOrientation(): No image loaded
Debug
core
2023-12-09T21:49:56+0100
OC_Image->loadFromFile, Default
```

Until 21:50:06

Interestingly enough, the on-screen error about the acknowledged duplicates doesn't seem to end up in the logs.

So I don't know what happens in the background right after opening the app, but when the JsonSerializable and JsonDateTime errors show up, is when the system starts to become unresponsive.

Hope that gives some indication.

**Comment by eldertek** [comment]
Can you add me on discord please ?, #eldertek

**Comment by keunes** [comment]
Also, it seems the app is re-fetching duplicates I time I open the app. A least: it says 'fetching items' and doesn't show any until the process is done.

**Comment by nursoda** [comment]
I see this in the Log on a NC 28.0.1 instance:

```
Error	core	NoUserException Backends provided no user object
Error while running background job (class: OCA\DuplicateFinder\BackgroundJob\CleanUpDB, arguments: )

Error	files	NoUserException Backends provided no user object
Backends provided no user object for matias
```

It may be that I one had a user matias, but there's no such user now. So there are some remnants that need to be cleaned out or handled properly even if data is inconsistent.

**Comment by nursoda** [comment]
Wouldn't pruning non-existent users from the duplicatefinder tables be more appropriate? At least there should be a way to accomplish this via `occ`.

**Comment by eldertek** [comment]
The duplicate finder doesn't store user information in its table; it only stores duplicate hashes. When a user requests their duplicates, the application checks if there are multiple files with the same hash in the user's directory.

It is more likely a nextcloud issue, not totally removing deleted user.

**Comment by keunes** [comment]
This might be an issue as well for my instance. But somehow I would be surprised if this causes my whole Nextcloud to hang (?) Happy to try again and get logs. Sorry I haven't followed up yet @eldertek, I've been travelling and was without access to my laptop.

**Comment by eldertek** [comment]
> This might be an issue as well for my instance. But somehow I would be surprised if this causes my whole Nextcloud to hang (?) Happy to try again and get logs. Sorry I haven't followed up yet @eldertek, I've been travelling and was without access to my laptop.

I will push my suggested fix, then update your app, and let me know how it goes.

**Comment by eldertek** [comment]
@nursoda also if you can add me on discord, we'll try to inspect deeply @eldertek ?

**Comment by nursoda** [comment]
Hi @eldertek, that's a kind offer, thanks. But I don't use discord and I already "solved" the issue by dropping the duplicatefinder tables and migrations :/

All I can tell you is that there was a user name "matias" within the duplicatefinder tables. However, those entries may be ancient: I use my 'test' instance to see which apps are available when a new NC major version is released, and to see if any apps on my other instances should be updated. I do sporadic tests, and sometimes create user accounts for tests (for me, friends and app devs). I assume that this user was created and removed a long time ago.

**Comment by eldertek** [comment]
> Hi @eldertek, that's a kind offer, thanks. But I don't use discord and I already "solved" the issue by uninstalling the app, dropping the duplicatefinder tables and its migrations, and re-installing it :/
> 
> All I can tell you is that there was a user name "matias" within the duplicatefinder tables. However, those entries may be ancient: I use my 'test' instance to see which apps are available when a new NC major version is released, and to see if any apps on my other instances should be updated. I do sporadic tests, and sometimes create user accounts for tests (for me, friends and app devs). I assume that this user was created and removed a long time ago.

Interesting I will look on myself =)

**Comment by eldertek** [comment]
This issue has been fixed btw, right now user can totally clean the database, then re-do the scan. I also limited fetching of duplicates to 40 (20 acknowledged, 20 unacknowledged), it will reload the entire page if there isn't any duplicates left.
