### ISSUE TITLE
Duplicates of other users on external storage are shown to me

### ISSUE THREAD

**Issue by nielstron** [eldertek/duplicatefinder#44]
I am sharing my nextcloud instance with another user. Both of us have external storage installed for storing most data. I have now recently encountered duplicates in the duplicate finder tag that do not belong to my own external storage!

Both storages are installed in the personal settings, i.e. not system wide. I can not see the content of the duplicates (likely because I should not have access to files of other users!) but I can see the whole path.

![image](https://github.com/eldertek/duplicatefinder/assets/20638630/fcce1291-d3ad-4fe6-bf97-9acd88f16eb3)

This is my root directory - the path "extern" does not exist but I happen to know that it exists for the other user.

![image](https://github.com/eldertek/duplicatefinder/assets/20638630/ca656c66-4483-4fb0-b552-dbc3492a807b)

Further, the paths are identical for the two files being shown as duplicates - which indicates to me that even the duplication detection appears broken there.

**Comment by eldertek** [comment]
Should be fixed by v1.1.5, only on Nextcloud 28.

**Comment by nielstron** [comment]
Thanks!
