### ISSUE TITLE
Memory greedy when NC has too much files

### ISSUE THREAD

**Issue by msviba** [eldertek/duplicatefinder#51]
Command `occ duplicates:find-all` leads to this error: PHP Fatal error:  Allowed memory size of 641728512 bytes exhausted (tried to allocate 20480 bytes) in /var/cloud/nc/apps/duplicatefinder/lib/Db/FileInfoMapper.php on line 44

Problem is when some user has too much files (in my case ~500000 files). They cant be all mapped into memory, what exactly happen in FileInfoMapper.

**Comment by eldertek** [comment]
I suggest you to allocate more memory to php.

**Comment by msviba** [comment]
I have allocated 612MB per process. How much is needed?

**Comment by eldertek** [comment]
Try 1024, 2048, test you'll see there is no specific requirement it depends of what you scan.
