### ISSUE TITLE
Showing deleted files as duplicate

### ISSUE THREAD

**Issue by msviba** [eldertek/duplicatefinder#55]
When I deleted a duplicated file and created it again, it's showing 3 files are duplicates. But one of them is already deleted.

Log: {"reqId":"8Rf8g18rtntmLXz3tas7","level":3,"time":"2024-02-21T23:32:29+00:00","remoteAddr":"192.168.21.5","user":"admin","app":"duplicatefinder","method":"GET","url":"/index.php/apps/duplicatefinder/api/duplicates/all?limit=50&page=1","message":"Error enriching FileInfo: /admin/files/photo-1495962637988-4be9db2af01f.jpeg","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"29.0.0.5","data":{"app":"duplicatefinder"}}

![image](https://github.com/eldertek/duplicatefinder/assets/1737311/1d810f15-911b-499a-a705-bf20e5c1ef41)

**Comment by eldertek** [comment]
Have you tried to delete all duplicates in admin and scan again ?

**Comment by msviba** [comment]
Yes

**Comment by Antua** [comment]
Same issue here. Did the `sudo occ duplicates:clear` and rerun `sudo occ duplicates:find-all` but the same issue reappears.

**Comment by eldertek** [comment]
Fix in July

**Comment by eldertek** [comment]
Hello, is the issue still ?
