### ISSUE TITLE
[Bug] - OCP\\BackgroundJob\\Job::$time must not be accessed before initialization

### ISSUE THREAD

**Issue by antonol68** [eldertek/duplicatefinder#57]
**Describe the bug**
The log throws this cron error daily 

**Expected behavior**
Should not have the error

**Error log**
{
  "reqId": "FTnzUIZQCuUVjlkHwrOf",
  "level": 3,
  "time": "2024-02-24T08:30:00+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "cron",
  "method": "",
  "url": "--",
  "message": "Exception thrown: Error",
  "userAgent": "--",
  "version": "28.0.2.5",
  "exception": {
    "Exception": "Error",
    "Message": "Typed property OCP\\BackgroundJob\\Job::$time must not be accessed before initialization",
    "Code": 0,
    "Trace": [
      {
        "file": "/usr/local/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/usr/local/www/nextcloud/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ],
          [
            "OC\\Log"
          ]
        ]
      }
    ],
    "File": "/usr/local/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
    "Line": 101,
    "CustomMessage": "Exception thrown: Error"
  },
  "id": "65d9b062ad91e"
}

**Versions**
- Nextcloud 28
- Duplicate Finder 1.1.8

**Comment by fotosik** [comment]
Same here, I will now see if deactivating the Duplicate Finder eliminates the bug.

**Comment by invario** [comment]
Confirmed. I disabled the app and the error stopped occurring.

**Comment by antonol68** [comment]
The cron error always happens twice 5 min apart at the same time in the morning 8:25 and 8:30.

**Comment by exstntlmsnthrp** [comment]
Any resolution to this, aside from uninstalling?

**Comment by eldertek** [comment]
I think you can disable cron for DupFinder in settings but not sure if it will stop making errors log.

I don't have lot of free time right now, I will fix the maximum of issues I can in April.

**Comment by riweckr** [comment]
:eyes:
