### ISSUE TITLE
[enh] Conditional File Ignoring for Detection

### ISSUE THREAD

**Issue by eldertek** [eldertek/duplicatefinder#6]
# Introduction
Missing feature for conditional file ignoring during detection. This functionality allowed users to bypass specific file types or naming patterns. Its reintroduction would provide more control in detection processes.

### Operators
[ ] - Equal string condition (=)
[ ] - Pattern condition (regex)

### Attributes
[ ] - By name
[ ] - By file type
[ ] - By file path 
[ ] - By hash

@asaage

**Comment by bw1faeh0** [comment]
This would be very useful to avoid such lists of "duplicate" files:

![image](https://github.com/eldertek/duplicatefinder/assets/29235332/b90b815c-51c5-49b6-91d3-3d72ef5251b2)

**Comment by bw1faeh0** [comment]
My comment was meant as '+1' for this feature request.

**Comment by sebastiencastermans** [comment]
> # Introduction
> Missing feature for conditional file ignoring during detection. This functionality allowed users to bypass specific file types or naming patterns. Its reintroduction would provide more control in detection processes.
> 
> ## Steps
> ### Operators
> [ ] - Equal string condition (=) [ ] - Pattern condition (regex)
> 
> ### Attributes
> [ ] - By name [ ] - By file type [ ] - By file path [ ] - By hash
> 
> @asaage

And where can we put this conditions ?

**Comment by eldertek** [comment]
I thought of a small icon at the right bottom, that open a menu to control all conditions and to show all ignored files.

**Comment by eldertek** [comment]
> This would be very useful to avoid such lists of "duplicate" files:
> 
> ![image](https://user-images.githubusercontent.com/29235332/269726729-b90b815c-51c5-49b6-91d3-3d72ef5251b2.png)
> 
> I would like to exclude files based on path and file extension.

I wonder about the relevance of this issue, given the recent addition of a feature to acknowledge duplicate

**Comment by asaage** [comment]
>  I wonder about the relevance of this issue, given the recent addition of a feature to acknowledge duplicate

I think that would still be very wellcome since the ```.nodupefinder``` file doesn't fit all use-cases and you had something like that in place already before.
