### ISSUE TITLE
[Bug] - Duplicate finder still finds duplicates after deletion

### ISSUE THREAD

**Issue by skunk-funk** [eldertek/duplicatefinder#61]
**Describe the bug**
Admittedly, might be a stretch to call this a bug? I am not aware of what the intended behavior is when somebody starts meddling.

Deleted all duplicates in terminal. Reran occ:scan and recognize and all that stuff. Every app in nextcloud correctly displays the correct photos and files now, but duplicate-finder still reports the same list of duplicates as it did prior to deletion.

This could cause some issues, as if a user goes to duplicate-finder they'll see a list of all the files. Only the remaining file will have a preview, and if they click "delete" on it, all copies of the file are gone.

**To Reproduce**
1. Run duplicate-finder
2. Run script to delete all duplicates except for one.
3. Clear data.
4. Re-run duplicate-finder
5. Go to duplicate-finder app in nextcloud, or run occ duplicates:list
6. Receive same list of duplicates, or be presented with phantom duplicates.

**Expected behavior**
After rescanning, duplicates should no longer be detected if they do not exist.

**Versions**
- [Nextcloud Hub 7](https://nextcloud.com/) (28.0.2)
- Duplicate Finder 1.1.8

**Additional context**

Thousands of duplicates - Not practical to click through them all for all users. Upload issue...

Might be a nice command to have one that deletes all duplicates except for the first one listed.

Getting gobs of this guy in the logs: Error enriching FileInfo:

**Comment by eldertek** [comment]
Hello, is the issue still happening on 1.2.5+ ?

**Comment by skunk-funk** [comment]
Unknown... I put a script on a Cronjob to fix the issue, I'll have to turn it off and create some duplicates to test it

**Comment by eldertek** [comment]
You should give a try, to newer version
