### ISSUE TITLE
[Bug] - Lists the same file (identical path) 17 times!

### ISSUE THREAD

**Issue by bernd-wechner** [eldertek/duplicatefinder#62]
**Describe the bug**
Yep, the same file is listed many times. They are duplicates but the self same file ;-) The same Path: is listed on each one.

**To Reproduce**
None to note. Describing the siutation on my system after installing and running the duplicate finder.

**Expected behavior**
That the Path: differ between the duplicates. The path looks like its root / is my home folder. I am an admin, and so it leaves the slight open question if these listed files are perhaps under other users. or that there is a database inetrity issue on my system?

**Screenshots**
Just the first three to illustrate:

![image](https://github.com/eldertek/duplicatefinder/assets/7296506/197fdc22-75b0-409a-adcd-037091ded74a)

**Versions**
- Nextcloud 28.0.3.2
- Duplicate Finder  1.1.8

**Comment by j-lakeman** [comment]
Possibly related to #65

**Comment by eldertek** [comment]
Hello, up ?

**Comment by eldertek** [comment]
Closing as should be fixed by 1.2.5+
