### ISSUE TITLE
Feature request: Folder based view

### ISSUE THREAD

**Issue by Gehmasse** [eldertek/duplicatefinder#64]
I am using this app for removing duplicates from my huge photo library.
There are not only duplicate single files, but whole duplicate folders or file stacks.
So I am performing the same actions again and again and do not proceed though.

I suggest adding a folder based view. It works similar to the existing view, but also includes other duplicates found in the same folders.
Then the user could perform a stack deletion then.

**Comment by eldertek** [comment]
Hello, I would be highly motivated to develop the feature swiftly with your support.

https://patreon.com/eldertek

**Comment by eldertek** [comment]
@Gehmasse I am not sure how to implemented this kind of feature, https://github.com/eldertek/duplicatefinder/issues/39 what do you think of 39 ? or do you have any specific ideas, to maintain a folder-based view ?

**Comment by Gehmasse** [comment]
Hi, this seems like the thing I search for. I will test your mentioned features and give you feedback :)

**Comment by eldertek** [comment]
I close this issue, you can continue on 39 :)
