### ISSUE TITLE
Same File Listed Twice as Duplicate

### ISSUE THREAD

**Issue by norsemangrey** [eldertek/duplicatefinder#65]
Hi, I recently started using the app. I have an issue where most of the "duplicates" found are actually just the same file(-path) listed twice.

![image](https://github.com/eldertek/duplicatefinder/assets/16608441/fbc3ba92-60e3-49e2-99c3-b1c28d25d0da)

**Comment by j-lakeman** [comment]
I can reproduce this. I'm assuming it's some sort of hash collision @eldertek? What algorithm is being used?
@norsemangrey as a workaround, you could _acknowledge_ them.

**Comment by eldertek** [comment]
Hello, is this happening on v1.2.3 ?

**Comment by eldertek** [comment]
Closing as should be fixed by 1.2.5+
