### ISSUE TITLE
[Enhancement] - Could not fetch settings

### ISSUE THREAD

**Issue by Breinich** [eldertek/duplicatefinder#66]
**Describe the bug**
The duplicate finder app can't find its settings from an account which is not admin, but from the admin's page they're available.

**To Reproduce**
1. Install the app from nextcloud app store
2. Run full scan by logged in with admin account
3. Switch to the other account
4. Run the full scan
5. See the error, e.g. at the attached screenshot

**Expected behavior**

Successful scan

**Screenshots**
![image](https://github.com/eldertek/duplicatefinder/assets/74102716/d8f8147c-f78f-4a80-bed2-cee26626fb6d)

**Versions**
- Nextcloud 28
- Duplicate Finder 1.1.8

**Comment by eldertek** [comment]
It's because a non-admin user, shouldn't be able to edit settings

**Comment by Breinich** [comment]
But shouldn't it be able to initiate a duplicate search, to check whether is there any duplicates among the currently uploaded files?

**Comment by eldertek** [comment]
In fact, it's a system wide scan, so a random user wouldn't be able to initiate it.

Maybe in future release, if a user scoped scan is implemented, the user will be able to initiate its own scan, but not right now.

**Comment by Breinich** [comment]
Okay, thanks.
