### ISSUE TITLE
.nodupefinder is not recursive

### ISSUE THREAD

**Issue by bnjetscrat** [eldertek/duplicatefinder#7]
The addition of `.nodupefinder` behaviour is great but this seems to only work on the level of the folder where the file is located.
This means that the app still checks the files inside of subfolders, which shouldn't be the awaited behaviour.

**Comment by eldertek** [comment]
@bnjetscrat should be fixed by [v1.0.5](https://github.com/eldertek/duplicatefinder/releases/tag/v1.0.5)

Update your application in app store
