### ISSUE TITLE
[Feature Request] Support for Nextcloud 29

### ISSUE THREAD

**Issue by cohenchris** [eldertek/duplicatefinder#70]
Hi, hoping to upgrade to Nextcloud 29 soon, but there's a message stating Duplicate Finder does not have a compatible version. Could you please add support for this?

By the way, this is an excellent app, I appreciate your work!

**Comment by eldertek** [comment]
Hi, I'm glad to hear you enjoy the app!

Could you please let me know if you are comfortable using the command line? If so, I can send you a package compatible with Nextcloud 29 for you to test, as I don't have NC 29 available for testing myself.

Thanks for your help!

**Comment by j-lakeman** [comment]
FYI can confirm it to be working on NC 29.

**Comment by cohenchris** [comment]
Hey @eldertek! I am more than glad to give it a try if @j-lakeman hasn't already.

**Comment by j-lakeman** [comment]
Confirmed working for 29.0.1 as well.

**Comment by eldertek** [comment]
@j-lakeman Just released in app store
