### ISSUE TITLE
GUI multiselect deletion needed 

### ISSUE THREAD

**Issue by DigitalLabs420** [eldertek/duplicatefinder#74]
Hi @eldertek, 

Thanks for the really helpful integration for Nextcloud! 

As previously desribed in posts in late 2023, a multi-select GUI element is desperately needed for deleting duplicates. 

I completely understand the time constraints and prior commitments, but this addition would immsenly increase the usefulness of the addon. 

Kind regards, 
DigitalLabs

**Comment by eldertek** [comment]
Hello, thank you for your help. However, to avoid duplicate issues, I kindly ask you to write in #39 and don't hesitate to propose how you would like the implementation to look. Additionally, I would be highly motivated to develop the feature swiftly with your support.

https://patreon.com/eldertek
