### ISSUE TITLE
`backgroundjob_interval_cleanup` and `backgroundjob_interval_find` in fresh installation differ from README

### ISSUE THREAD

**Issue by j-lakeman** [eldertek/duplicatefinder#75]
**To Reproduce**
1. fresh install of Duplicate Finder
2. go to settings/admin/duplicatefinder
3. Scroll down to  “Background Job Cleanup Interval (seconds)”
4. See “172800” differing from README
5. same for “Background Job Find Duplicates Interval (seconds)”, seem to be swapped in either

**Comment by eldertek** [comment]
Just edited the readme
