### ISSUE TITLE
Use with managed hosting?

### ISSUE THREAD

**Issue by elsiehupp** [eldertek/duplicatefinder#77]
I have a managed Nextcloud instance, meaning I have full administrator access to the web interface, but I don't have any immediate access to the command line. (I could probably ask my hosting provider to do specific things for me, though.)

Is there a way to use this application without the command line? If so, could that usage be added to the documentation? And, if not, could you look into what would be involved in making the application fully configurable and usable from the Nextcloud web interface alone? Thanks!

**Comment by eldertek** [comment]
Hello, from settings you can edit all duplicate finder settings. And from the user interface there is an icon duplicate where you can access the whole detected duplicate.

The app could be used cli-less

**Comment by elsiehupp** [comment]
Okay, I see. It just took a second to initialize. (I guess it does not automatically run an initial scan?)

It could still be nice to have some explanation of the web interface in the documentation.

**Comment by eldertek** [comment]
It is planned I just don't have many times, yes the app needs some seconds to intialize fully .
