### ISSUE TITLE
Not clear what exactly is happening. This can lead to irricoverable mistakes. 

### ISSUE THREAD

**Issue by bobboau** [eldertek/duplicatefinder#78]
OK, so this is an app for DELETING files. We should be VERY clear about what is happening, and the use cases of the users and what people will be doing.

So, let's consider what I think is probably the primary use case. A user has a bunch of files duplicated and they want there to be one file with a given hash remaining when they are done of each of them.

If there are two instances of a file with the same hash. What will the user see? Two files on the screen for that one hash? If they select all and delete is that going to delete EVERY instance of that file from the server? Isn't the goal to remove duplicates? Shouldn't one of them be left? That's what the user wants to do, right? This is an irreversible action and it doesn't feel like it's realy super clear what is going to happen. 

I've noticed when I hit the delete button the same set of files comes up again. I don't know if that is a separate pair of files. If I hit delete on the second one twice I get an error message. Is that because I tried deleting the same file twice? And the second time it didn't work because i deleted it the first time? If I alternate I don't get that error (yay, no error means good, right? Thinks the user), is that because I just permanently deleted all instances of a file I was trying to reduce to one instance? Why is it possible using this app that I can delete (quite easily) all instances of a file?

Once I delete one of a pair it is no longer duplicated. If it's not duplicated it shouldn't be an option for me to delete the last remaining copy of the file.

I'm not sure what my suggestion should be but I THINK I have irricoverably lost a few files because the user experience is not super clear on what is happening and what you are doing when using the app. The documentation doesn't go into any detail or provide any warnings. I'm not super mad or anything because I don't think I lost anything super important but the next person who comes along might accidentally delete their wedding pictures or the last picture of their mom before she died or something. As this app currently is I think it's kinda dangerous. It's almost like a script that has an 'rm -rf /' in it.

The hash based identification of duplicates seems to work well but I think what we do with it after that could use some work. Maybe some sort of batch operation and you have the app make sure there is at least one instance of a file left? Maybe put files in a holding zone rather than actually deleting them so mistakes can be undone? (Purge the holding zone to recover space when the user is happy). Maybe we shouldn't be putting the user in the position of picking which file to delete, but maybe the user should pick which file to keep?

And let's remember the big use case. Someone has 20,000 files and 10,000 hashes. Kind of feels like there should be a way to automatically just pick the first one on all of them (theres probably a bunch of strategies you could have the user pick from). As long as it doesn't delete the last instance of the file the app could (relatively) easily undo anything it does.

Try not to take this as harsh criticism. I am trying to be productive and I think this app is pretty close to being immensely useful. But there are some major usability issues that need to be addressed.

**Comment by eldertek** [comment]
I will implement a new feature that adds a verification step to prevent users from inadvertently deleting all instances of a file with a given hash. This verification will alert the user if their action would result in the deletion of all existing copies of a file. 

Do you need anything else ?
