### ISSUE TITLE
Duplicate hashes with no way to reset them

### ISSUE THREAD

**Issue by rbfii** [eldertek/duplicatefinder#8]
I have nearly 4GB of images all with the same hash. This appears to have happened during an upload after I had installed the Duplicate Finder.
Note that folders I imported are not effected and images have unique hashes and are displaying correctly in the UI
![Screenshot from 2023-09-04 16-16-33](https://github.com/eldertek/duplicatefinder/assets/11374145/e4f2d139-841d-4d02-88ba-8deaa9475a23)

**Comment by eldertek** [comment]
Can you clear duplicates from OCC then find duplicates, please send the output 🙂

**Comment by eldertek** [comment]
Closing : no response.
