### ISSUE TITLE
FR: improve handling on massive results

### ISSUE THREAD

**Issue by steadfasterX** [eldertek/duplicatefinder#97]
Hey again 😎

I have hundreds of duplicates (>8000) which I want to handle. Based on the path i want to remove the dups and keep the one in a specific path. Atm I have to walk through each dup found on the left and then going through those i want to delete. Click again on left and so on.. impossible doing that for 8000 findings. I know one can use the cli for that but i was wondering if the UI handling could be improved in a way where u can remove all those from a specific path / folder if there is at least 1 other file? Does that make any sense 🤔?

Thx in advance

EDIT:

I have imported photos from several aources and mixed up some paths etc.
I have several folders which should never be touched like Camera, Instagram and a few more.. then i have photos which are in the root dir which were there before those other folders exist and also folders for other imports i did (e.g a google photos export/import)

So actually the most easiest solution in my case would be: 

1. I can specify several folders as "origin" 
2. origin folders would be displayed in the results but wont get touched ever and no removal button 
3. I would need an option which can delete all duplicates which have a dup in any origin folder in 1 run. So you see a preview what would happen first and then can optionally deselect before the removal takes place
4. A dry-run would be a nice option as well where it shows only what would happen and why (like: file ABC was found in origin folder AAA and has dups in BBB and CCC which going to be removed)

**Comment by KruyKaze** [comment]
Or maybe an option : if **_identical_** file is found, delete newer version

**Comment by steadfasterX** [comment]
@KruyKaze hm no that wouldnt work in my case. I have imported photos from several aources and mixed up some paths etc. on different dates.
I have several folders which should never be touched like Camera, Instagram and a few more.. then i have photos which are in the root dir which were there before those other folders exist and also folders for other imports i did (e.g a google photos export/import)

So actually the most easiest solution in my case would be: 

1. I can specify several folders as "origin" 
2. origin folders would be displayed in the results but wont get touched ever and no removal button 
3. I would need an option which can delete all duplicates which have a dup in any origin folder in 1 run. So you see a preview what would happen first and then can optionally deselect before the removal takes place
4. A dry-run would be a nice option as well where it shows only what would happen and why (like: file ABC was found in origin folder AAA and has dups in BBB and CCC which going to be removed)

**Comment by eldertek** [comment]
Just to clarify, am I right ?

You have thousands of duplicate files and need a simpler way to remove them. You want to define certain "origin" folders that must never be touched. Any duplicates found outside these origin folders should be removable in one go if a matching file exists in an origin folder. Ideally, you'd see a preview of what will be deleted, and a dry run would show which files would be removed and why. This would greatly streamline handling thousands of duplicate entries.

**Comment by steadfasterX** [comment]
exactly :)

**Comment by eldertek** [comment]
Added in v1.2.9

**Comment by steadfasterX** [comment]
hi @eldertek ! many thanks for working on that topic!! really appreciated. 
I have installed v1.3.0 and I can see the Origin folder setting which itself protects from deleting a file within that folder. cool! I haven't tested that but I assume this will also protect when using the CLI command?

but I cannot seem to find the possibility to do such a deletion for all hashes in one run. as mentioned I see at the left tons of (thousands) duplicates / hashes which I would need to acknowledge one by one. 
that alone will take weeks. so my idea was an option which offers a deletion of all duplicates in one run - not hash by hash but for all hashes found. I am totally fine when this would work on the CLI only!

or maybe I miss something here? I also tried on the CLI but cannot find anything related. could you give me a short guide how I can handle thousands of duplicates with different hashes?

just to be clear: I do not have thousands of dups for a **single** hash. each hash has just a few (like 5-10) duplicates but I have thousands of findings for **different** hashes. maybe that's the thing which wasn't clear enough described by me?!?

**Comment by eldertek** [comment]
Sorry, I indeed missed part of your request, especially regarding the dry-run feature and the ability to delete all duplicate files outside of protected folders in one go.

I’ll think about how to integrate this into the CLI, and potentially into the web interface as well. However, I won’t be able to address it immediately!

Thanks for your patience !

**Comment by steadfasterX** [comment]
many thanks dude! really appreciated

**Comment by eldertek** [comment]
Fixed in v1.3.1: This version introduces bulk deletion feature
